// Trainer feature exports
export * from './ClientsTab'
export * from './ClientTable'
export * from './ClientFilters'
export * from './ClientsHeader'
export * from './NewClientDialog'
export * from './EditClientDialog'
export * from './ClientHistoryDialog'
export * from './TrainerAssistant'
