import { CalendarEvent, Chat, Client, DashboardStat, Exercise, RecentClient, UpcomingSession } from "@/types/trainer"
import { Calendar, DollarSign, TrendingUp, Users } from "lucide-react"

export const FALLBACK_EXERCISES: Exercise[] = [
  {
    id: "push-up",
    name: "Push Up",
    target_muscles: ["Pectorales"],
    body_parts: ["Torso"],
    equipments: [],
    secondary_muscles: ["Tríceps", "Hombros"],
    description: "Flexiones clásicas utilizando el peso corporal.",
  },
  {
    id: "squat",
    name: "Sentadilla",
    target_muscles: ["Cuádriceps"],
    body_parts: ["Piernas"],
    equipments: ["Peso corporal"],
    secondary_muscles: ["Glúteos", "Isquiotibiales"],
    description: "Sentadilla básica manteniendo la espalda recta.",
  },
  {
    id: "plank",
    name: "Plancha",
    target_muscles: ["Core"],
    body_parts: ["Abdomen"],
    equipments: [],
    secondary_muscles: ["Hombros"],
    description: "Plancha isométrica para fortalecer el core.",
  },
]

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 1,
    title: "Entrenamiento con María González",
    description: "Sesión presencial de fuerza y cardio",
    date: "2024-01-15",
    time: "09:00",
    type: "training",
    clientId: 1,
    clientName: "María González",
    isPresential: true,
    status: "pending",
    color: "bg-blue-500",
  },
  {
    id: 2,
    title: "Enviar rutina a Carlos Ruiz",
    description: "Nueva rutina de hipertrofia",
    date: "2024-01-15",
    time: "14:00",
    type: "routine_send",
    clientId: 2,
    clientName: "Carlos Ruiz",
    status: "pending",
    color: "bg-green-500",
  },
  {
    id: 3,
    title: "Pago mensual - Ana López",
    description: "Renovación de plan mensual",
    date: "2024-01-16",
    time: "10:00",
    type: "payment",
    clientId: 3,
    clientName: "Ana López",
    status: "pending",
    color: "bg-orange-500",
  },
  {
    id: 4,
    title: "Entrenamiento con Carlos Ruiz",
    description: "Sesión de cardio por su cuenta",
    date: "2024-01-16",
    time: "16:00",
    type: "training",
    clientId: 2,
    clientName: "Carlos Ruiz",
    isPresential: false,
    status: "pending",
    color: "bg-purple-500",
  },
]

export const UPCOMING_SESSIONS: UpcomingSession[] = [
  {
    id: 1,
    client: "María González",
    time: "09:00",
    type: "Entrenamiento Personal",
    avatar: "/fit-woman-outdoors.png",
  },
  {
    id: 2,
    client: "Carlos Ruiz",
    time: "10:30",
    type: "Rutina de Fuerza",
    avatar: "/fit-man-gym.png",
  },
  {
    id: 3,
    client: "Ana López",
    time: "14:00",
    type: "Cardio + Tonificación",
    avatar: "/woman-workout.png",
  },
]

export const CLIENTS: Client[] = [
  {
    id: 1,
    name: "María González",
    email: "maria.gonzalez@email.com",
    phone: "+34 612 345 678",
    status: "Activo",
    joinDate: "15 Ene 2024",
    lastSession: "2 días",
    nextSession: "Mañana 09:00",
    progress: 85,
    goal: "Pérdida de peso",
    avatar: "/fit-woman-outdoors.png",
    sessionsCompleted: 24,
    totalSessions: 30,
    plan: "Premium",
  },
  {
    id: 2,
    name: "Carlos Ruiz",
    email: "carlos.ruiz@email.com",
    phone: "+34 623 456 789",
    status: "Activo",
    joinDate: "8 Feb 2024",
    lastSession: "1 día",
    nextSession: "Hoy 10:30",
    progress: 92,
    goal: "Ganancia muscular",
    avatar: "/fit-man-gym.png",
    sessionsCompleted: 18,
    totalSessions: 20,
    plan: "Básico",
  },
  {
    id: 3,
    name: "Ana López",
    email: "ana.lopez@email.com",
    phone: "+34 634 567 890",
    status: "Pendiente",
    joinDate: "22 Mar 2024",
    lastSession: "5 días",
    nextSession: "Por agendar",
    progress: 67,
    goal: "Tonificación",
    avatar: "/woman-workout.png",
    sessionsCompleted: 12,
    totalSessions: 16,
    plan: "Premium",
  },
  {
    id: 4,
    name: "Luis Martín",
    email: "luis.martin@email.com",
    phone: "+34 645 678 901",
    status: "Activo",
    joinDate: "5 Abr 2024",
    lastSession: "1 día",
    nextSession: "Mañana 16:00",
    progress: 78,
    goal: "Resistencia",
    avatar: "/man-gym.png",
    sessionsCompleted: 15,
    totalSessions: 20,
    plan: "Básico",
  },
  {
    id: 5,
    name: "Carmen Silva",
    email: "carmen.silva@email.com",
    phone: "+34 656 789 012",
    status: "Activo",
    joinDate: "12 May 2024",
    lastSession: "3 días",
    nextSession: "Viernes 11:00",
    progress: 73,
    goal: "Rehabilitación",
    avatar: "/fit-woman-outdoors.png",
    sessionsCompleted: 8,
    totalSessions: 12,
    plan: "Premium",
  },
  {
    id: 6,
    name: "Diego Morales",
    email: "diego.morales@email.com",
    phone: "+34 667 890 123",
    status: "Inactivo",
    joinDate: "28 Jun 2024",
    lastSession: "2 semanas",
    nextSession: "Sin agendar",
    progress: 45,
    goal: "Pérdida de peso",
    avatar: "/fit-man-gym.png",
    sessionsCompleted: 6,
    totalSessions: 16,
    plan: "Básico",
  },
]

export const DASHBOARD_STATS: DashboardStat[] = [
  { title: "Alumnos Activos", value: "24", change: "+3", icon: Users, color: "text-primary" },
  { title: "Sesiones Hoy", value: "8", change: "+2", icon: Calendar, color: "text-primary" },
  { title: "Ingresos Mes", value: "$4,250", change: "+12%", icon: DollarSign, color: "text-primary" },
  { title: "Progreso Promedio", value: "82%", change: "+5%", icon: TrendingUp, color: "text-primary" },
]

export const RECENT_CLIENTS: RecentClient[] = [
  {
    id: 1,
    name: "María González",
    status: "Activo",
    lastSession: "2 días",
    progress: 85,
    avatar: "/fit-woman-outdoors.png",
  },
  {
    id: 2,
    name: "Carlos Ruiz",
    status: "Activo",
    lastSession: "1 día",
    progress: 92,
    avatar: "/fit-man-gym.png",
  },
  {
    id: 3,
    name: "Ana López",
    status: "Pendiente",
    lastSession: "5 días",
    progress: 67,
    avatar: "/woman-workout.png",
  },
  {
    id: 4,
    name: "Luis Martín",
    status: "Activo",
    lastSession: "1 día",
    progress: 78,
    avatar: "/man-gym.png",
  },
]

export const DEFAULT_CHAT_CONVERSATIONS: Chat[] = [
  {
    id: 1,
    clientId: 1,
    clientName: "María González",
    clientAvatar: "/fit-woman-outdoors.png",
    lastMessage: "¡Perfecto! Nos vemos mañana a las 9",
    lastMessageTime: "10:30",
    unreadCount: 0,
    isOnline: true,
    messages: [
      {
        id: 1,
        senderId: 1,
        senderName: "María González",
        message: "Hola! ¿Podemos cambiar la rutina de mañana?",
        timestamp: "09:15",
        isRead: true,
        isTrainer: false,
      },
      {
        id: 2,
        senderId: "trainer",
        senderName: "Trainer",
        message: "¡Hola María! Por supuesto, ¿qué te gustaría cambiar?",
        timestamp: "09:18",
        isRead: true,
        isTrainer: true,
      },
      {
        id: 3,
        senderId: 1,
        senderName: "María González",
        message: "Me gustaría enfocarme más en cardio esta semana",
        timestamp: "09:20",
        isRead: true,
        isTrainer: false,
      },
      {
        id: 4,
        senderId: "trainer",
        senderName: "Trainer",
        message: "Perfecto! Vamos a hacer 30 min de cardio y 15 min de fuerza. ¿Te parece bien a las 9:00 AM?",
        timestamp: "09:25",
        isRead: true,
        isTrainer: true,
      },
      {
        id: 5,
        senderId: 1,
        senderName: "María González",
        message: "¡Perfecto! Nos vemos mañana a las 9",
        timestamp: "10:30",
        isRead: true,
        isTrainer: false,
      },
    ],
    isFavorite: true,
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Carlos Ruiz",
    clientAvatar: "/fit-man-gym.png",
    lastMessage: "¿Puedes enviarme la rutina de hoy?",
    lastMessageTime: "08:45",
    unreadCount: 2,
    isOnline: false,
    messages: [
      {
        id: 1,
        senderId: 2,
        senderName: "Carlos Ruiz",
        message: "Buenos días! ¿Cómo estás?",
        timestamp: "08:30",
        isRead: false,
        isTrainer: false,
      },
      {
        id: 2,
        senderId: 2,
        senderName: "Carlos Ruiz",
        message: "¿Puedes enviarme la rutina de hoy?",
        timestamp: "08:45",
        isRead: false,
        isTrainer: false,
      },
    ],
    isFavorite: false,
  },
  {
    id: 3,
    clientId: 3,
    clientName: "Ana López",
    clientAvatar: "/woman-workout.png",
    lastMessage: "Gracias por la sesión de ayer",
    lastMessageTime: "Ayer",
    unreadCount: 0,
    isOnline: false,
    messages: [
      {
        id: 1,
        senderId: 3,
        senderName: "Ana López",
        message: "Gracias por la sesión de ayer, me siento genial!",
        timestamp: "Ayer 18:30",
        isRead: true,
        isTrainer: false,
      },
      {
        id: 2,
        senderId: "trainer",
        senderName: "Trainer",
        message: "¡Me alegra escuchar eso! Sigue así 💪",
        timestamp: "Ayer 19:00",
        isRead: true,
        isTrainer: true,
      },
    ],
    isFavorite: false,
  },
  {
    id: 4,
    clientId: 4,
    clientName: "Luis Martín",
    clientAvatar: "/man-gym.png",
    lastMessage: "¿A qué hora es mañana?",
    lastMessageTime: "2 días",
    unreadCount: 1,
    isOnline: true,
    messages: [
      {
        id: 1,
        senderId: 4,
        senderName: "Luis Martín",
        message: "Hola, ¿a qué hora es la sesión de mañana?",
        timestamp: "2 días",
        isRead: false,
        isTrainer: false,
      },
    ],
    isFavorite: false,
  },
]
